version: '3.8'

services:
  db-dev:
    image: postgres:13
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: cong2001
      POSTGRES_DB: nest
    networks:
      - authservice

networks:
  authservice:
